/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 tree1.gltf --transform
Author: atrodler (https://sketchfab.com/atrodler)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/maple-tree-4b27adcf92f644bdabf8ecc6c5bef399
Title: Maple tree
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/tree1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Material2_3.geometry} material={materials.sugar_maple_leaf} />
      <mesh geometry={nodes.Material2.geometry} material={materials.Groundcover_Wood_Mix} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_1.geometry} material={materials.grass} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_2.geometry} material={materials.sugar_maple_bark} position={[0.895, 90.501, -0.606]} rotation={[-2.288, -0.89, 2.785]} />
    </group>
  )
}

useGLTF.preload('/tree1-transformed.glb')
