/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 modelDraco.gltf --transform
Author: Frybrix (https://sketchfab.com/Frybrix)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tree-1d419eb4c9d34fc1a7f1e88d6ea8d55a
Title: Tree
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/modelDraco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.CTBOL} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.Grass} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.KPOHA} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.LISTBA} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Ground_and_rock} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
    </group>
  )
}

useGLTF.preload('/modelDraco-transformed.glb')
